<a href="https://colab.research.google.com/github/lalithakre/Normalization-in-ML/blob/main/Normalization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
data=[[5,200],[2,359],[8,120],[1,23]]
from sklearn.preprocessing import MinMaxScaler
scale=MinMaxScaler()
data1=scale.fit_transform(data)
data1

array([[0.57142857, 0.52678571],
       [0.14285714, 1.        ],
       [1.        , 0.28869048],
       [0.        , 0.        ]])

In [4]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
data2=ss.fit_transform(data)
data2

array([[ 0.36514837,  0.19903411],
       [-0.73029674,  1.4907249 ],
       [ 1.46059349, -0.4508732 ],
       [-1.09544512, -1.23888581]])

In [7]:
"""encoding:
is a technique of converting categorical variables into numerical values so that it could be easily fitted to a machine leaning model.
"""

'encoding:\nis a technique of converting categorical variables into numerical values so that it could be easily fitted to a machine leaning model.'

In [8]:
""""Types of encoding:
One hot encoding: single one is '1' other bits are '0'
"""

'"Types of encoding:\nOne hot encoding: single one is \'1\' other bits are \'0\'\n\n'

In [23]:
import numpy as np
data=['blue','red','yellow','black','blue']
data4=np.array(data)
from sklearn.preprocessing import OneHotEncoder
enc=OneHotEncoder()
data3=enc.fit_transform(data4[:,np.newaxis]).toarray()
data3

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])