<a href="https://colab.research.google.com/github/lalithakre/Normalization-in-ML/blob/main/PreProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
data=[[5,200],[2,359],[8,120],[1,23]] #2D list
from sklearn.preprocessing import MinMaxScaler
scale=MinMaxScaler() 
data1=scale.fit_transform(data)
data1

array([[0.57142857, 0.52678571],
       [0.14285714, 1.        ],
       [1.        , 0.28869048],
       [0.        , 0.        ]])

In [ ]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
data2=ss.fit_transform(data)
data2

array([[ 0.36514837,  0.19903411],
       [-0.73029674,  1.4907249 ],
       [ 1.46059349, -0.4508732 ],
       [-1.09544512, -1.23888581]])

In [ ]:
"""encoding:
is a technique of converting categorical variables into numerical values so that it could be easily fitted to a machine leaning model.
"""

'encoding:\nis a technique of converting categorical variables into numerical values so that it could be easily fitted to a machine leaning model.'

In [ ]:
""""Types of encoding:
One hot encoding: single one is '1' other bits are '0'
"""

'"Types of encoding:\nOne hot encoding: single one is \'1\' other bits are \'0\'\n\n'

In [ ]:
import numpy as np #this library is used to perform operations on array
data=['blue','red','yellow','black','blue'] #list
data4=np.array(data) #converting list into an array
from sklearn.preprocessing import OneHotEncoder #for pre processing
enc=OneHotEncoder() #intializing in enc variable 
data3=enc.fit_transform(data4[:,np.newaxis]).toarray() 
data3

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [ ]:
"""
Ordinal encoding :
#if you want ordering encoding
"""

'\nOrdinal encoding :\n\n'

In [8]:
import numpy as np
data=['professor','assistantprofessor','director','associateprofessor']#list
data=np.array(data)#array
arr=data.reshape(-1,1)#reshaping
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
data5=oe.fit_transform(arr)
data5.astype(int)

array([[3],
       [0],
       [2],
       [1]])

In [ ]:
# to check outliers in dataset

In [16]:
data=[1,224,122,234,234,234,423]
import numpy as np
q1=np.percentile(data,25)
q2=np.percentile(data,75)
i=q2-q1
max=q2+(1.5*i)
min=q1-(1.5*i)
outlier=[]
for i in data:
  if i>max or i<min:
    outlier.append(i)
outlier

[1, 423]